baseURL = "https://timcarr.net/"
languageCode = "en-us"
title = "timcarr.net"
theme = "mainroad"
paginate = "10" # Number of posts per page

googleAnalytics = "UA-156906429-1" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Tim Carr"
  bio = "Tim Carr is a Cloud Native Field Engineer with VMware"
  avatar = "img/headshot.jpeg"

[Params]
  subtitle = "...helping out with technical things" # Subtitle of your site. Used in site header
  description = "timcarr.net - helping out with technical things." # Site description. Used in meta description
  copyright = "Tim Carr" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "01-02-2006" # Change the format of dates
#  mathjax = true # Enable MathJax
#  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
#  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
   highlightColor = "#0134A6" #23395d #e22d30 # Override highlight color
#  customCSS = ["css/custom.css"] # Include custom CSS files
#  customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "left" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
#  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  widgets = ["recent", "categories", "taglist", "social", "languages"]
[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "timmycarr"
#  linkedin = "timmycarr"
  github = "timmycarr"
#  email = "tim@timcarr.net"

# Custom social links
#[[Params.widgets.social.custom]]
#  title = "Youtube"
#  url = "https://youtube.com/user/username"
#  icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

#[[Params.widgets.social.custom]]
#  title = "My Home Page"
#  url = "http://timcarr.net"
